Fix whitespace
Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/base/scripts/rtai-load.in b/base/scripts/rtai-load.in
--- a/base/scripts/rtai-load.in
+++ b/base/scripts/rtai-load.in
@@ -58,12 +58,12 @@ stanza=`grep "^[$spc]*$target_name[$spc]*:" $run_info_file`
 if test "x$stanza" = x; then
    have_user_command_option=`cut -d: -f1 .runinfo | grep user_command`
    if test "x$have_user_command_option" = x; then
-       echo "passo di qui"
-       echo "rtai-load: cannot find run info for target $target_name"
-       exit 2
+	echo "passo di qui"
+	echo "rtai-load: cannot find run info for target $target_name"
+	exit 2
    else
-       target_name=user_command
-       stanza=`grep "^[$spc]*$target_name[$spc]*:" $run_info_file`
+	target_name=user_command
+	stanza=`grep "^[$spc]*$target_name[$spc]*:" $run_info_file`
    fi
 fi
 
@@ -129,16 +129,16 @@ cleanup () {
 
     if test \! "x$children_pids" = x; then
 #      $sudo kill -SIGINT $children_pids > /dev/null 2>&1 see comment below
-       $sudo kill -INT $children_pids > /dev/null 2>&1
-       children_pids=""
-       sleep 1
+	$sudo kill -INT $children_pids > /dev/null 2>&1
+	children_pids=""
+	sleep 1
     fi
     if test \! "x$inslist" = x; then
-       for mod in $inslist ; do
+	for mod in $inslist ; do
 	  test $verbose = 1 && echo "+ $rmmod $mod"
 	  $sudo $rmmod $mod
-       done
-       inslist=""
+	done
+	inslist=""
     fi
 }
 
@@ -159,20 +159,20 @@ while test -n "$target_deps" ; do
      # the scheduler or not needed. Obviously, we should _always_ find
      # the scheduler...
      if test -r $rtai_moddir/rtai_$mod$modext; then
-        test $verbose = 1 && echo "+ $insmod $rtai_moddir/rtai_$mod$modext"
-        $sudo $insmod $rtai_moddir/rtai_$mod$modext
+	 test $verbose = 1 && echo "+ $insmod $rtai_moddir/rtai_$mod$modext"
+	 $sudo $insmod $rtai_moddir/rtai_$mod$modext
 	if test $? = 0 ; then
-           inslist="rtai_$mod $inslist"
-           loadlist="$loadlist $mod"
+	    inslist="rtai_$mod $inslist"
+	    loadlist="$loadlist $mod"
 	else
 	   echo "ERROR: cannot load $rtai_moddir/rtai_$mod$modext"
 	   break
-        fi
+	 fi
      elif `$modprobe -n $mod > /dev/null 2>&1`; then
-        test $verbose = 1 && echo "+ $modprobe $mod"
-        $sudo $modprobe $mod
-        inslist="$mod $inslist"
-        loadlist="$loadlist $mod"
+	 test $verbose = 1 && echo "+ $modprobe $mod"
+	 $sudo $modprobe $mod
+	 inslist="$mod $inslist"
+	 loadlist="$loadlist $mod"
      fi
   fi
 done
@@ -187,18 +187,18 @@ while test -n "$target_info" ; do
     push)
 
 	mod=`basename $2 $modext`
-        if test -r $rtai_moddir/$mod$modext; then
-           modpath="$rtai_moddir/$mod"
-        elif test -r $user_moddir/$mod$modext; then
-           modpath="$user_moddir/$mod"
-        else
-           modpath="$mod"
-        fi
+	 if test -r $rtai_moddir/$mod$modext; then
+	    modpath="$rtai_moddir/$mod"
+	 elif test -r $user_moddir/$mod$modext; then
+	    modpath="$user_moddir/$mod"
+	 else
+	    modpath="$mod"
+	 fi
 	if `echo $loadlist | grep -vq "\\b$mod\\b"`; then
 	   test $verbose = 1 && echo "+ $insmod $modpath$modext"
 	   $sudo $insmod $modpath$modext
 	   if test $? = 0; then
-              loadlist="$loadlist $mod"
+		loadlist="$loadlist $mod"
 	      inslist="$mod $inslist"
 	   else
 	      echo "ERROR: cannot load $modpath$modext"
@@ -210,42 +210,42 @@ while test -n "$target_info" ; do
 
 	shift
 	if test "x$*" = x; then
-           rmlist=`echo $inslist | cut -s -f1 -d' '`
-        else
-           rmlist=$*
+	    rmlist=`echo $inslist | cut -s -f1 -d' '`
+	 else
+	    rmlist=$*
 	fi
-        _inslist="$inslist"
+	 _inslist="$inslist"
 	if test \! "x$rmlist" = x; then
-           for mod in $rmlist ; do
+	    for mod in $rmlist ; do
 	      test $verbose = 1 && echo "+ $rmmod $mod"
 	      $sudo $rmmod $mod && _inslist=`echo $_inslist | sed -e "s,$mod,,g"`
-           done
-        inslist="$_inslist"
+	    done
+	 inslist="$_inslist"
 	fi
 	;;
 
     popall|flush)
 
-        cleanup
+	 cleanup
 	;;
 
     *)
 
-        case "$1" in
+	 case "$1" in
 	  exec|spawn) shift ;;
 	  klog) set -- \! tail -f /var/log/messages ;;
 	esac
 	e=`echo $* | sed -e "s,^[$spc]*![$spc]*\\(.*\\)$,\\1,"`
-        test "$e" = "$*" && suflag= || suflag=$sudo
+	 test "$e" = "$*" && suflag= || suflag=$sudo
 	set -- $e
 	e=`echo $* | sed -e "s,\\(.*\\)&[$spc]*$,\\1,"`
-        test "$e" = "$*" && waitflag=1 || waitflag=0
+	 test "$e" = "$*" && waitflag=1 || waitflag=0
 	set -- $e
 	test $verbose = 1 && echo "+ spawning command ($*)"
 	if test $waitflag = 1; then
-           $suflag $*
-        else
-           $suflag $* &
+	    $suflag $*
+	 else
+	    $suflag $* &
 	   children_pids="$! $children_pids"
 	fi
 	;;
